pkg/cvc/v1alpha1/build.go
pkg/cvc/v1alpha1/kubernetes.go
pkg/cvc/v1alpha1/utils.go
pkg/iscsi/v1alpha1/iscsi_extra_utils.go
pkg/iscsi/v1alpha1/iscsi_util.go
pkg/payload/v1alpha1/delete.go
pkg/service/v1alpha1/controller.go
pkg/service/v1alpha1/node.go
pkg/service/v1alpha1/service.go
pkg/utils/v1alpha1/maya.go
pkg/utils/v1alpha1/utils.go
pkg/volume/v1alpha1/build.go

This PR updates the functionality for volume Creation/Deletion. Following are the APIs which have been updated:
1) CreateVolume(): Create CStorVolumeClaim(CVC) CR on receiving Create Volume Request at Controller. This will be created with empty nodeID and status marked as pending. Once this API responds success kubernetes sends a NodePublishVolume() request.
CVC Controller at maya waits for NodeID to be updated in the CVC to create the required volume components.
2) NodePublishVolume(): Patch nodeID to the previously created CVC CR and wait for status to be updated to bound by maya. The bound status implies that the required volume components have been created. Once the status is changed to bound, steps to mount the volume are processed
3) NodeUnPublishVolume(): Unmount the volume and …

feat(ProvisionVolume): Update Volume Provisioning and Deletion using CVC

---

deploy/percona.yaml
deploy/pvc.yaml
deploy/sc.yaml
deploy/sqltest_configmap.yaml

This PR adds the following example yamls for a user to test basic OpenEBS CSI functionality:
1) Storage class with CSI provisioner
2) PVC with above Storage Class
3) Percona app with above PVC
4) sqltest configmap yaml for use in above percona app

chore(config): add sample yamls for creating CSI based volumes

---

pkg/apis/openebs.io/maya/v1alpha1/cstor_volume_claim.go
pkg/cvc/v1alpha1/build.go
pkg/service/v1alpha1/controller.go
pkg/utils/v1alpha1/maya.go

- Update CVC schema struct with `ReplicaCount` type.
- Add StoragePoolClaim (CstorPoolClusterClaim) name in CVC label
while building cstor volume claim.
**CStorVolumeClaim object:**
```yaml
apiVersion: openebs.io/v1alpha1
kind: CStorVolumeClaim
metadata:
annotations:
openebs.io/config-class: openebs-cstor-sparse-auto
openebs.io/volumeID: pvc-d030e3e4-a700-11e9-b527-42010a800279
creationTimestamp: "2019-07-15T13:02:34Z"
finalizers:
- cvc.openebs.io/finalizer
generation: 3
labels:
openebs.io/storage-pool-claim: cstor-sparse-pool
name: pvc-d030e3e4-a700-11e9-b527-42010a800279
namespace: openebs
resourceVersion: "5114188"
selfLink: /apis/openebs.io/v1alpha1/namespaces/openebs/cstorvolumeclaims/pvc-d030e3e4-a700-11e9-b527-42010a800279
uid: d03bfcae-a700-11e9-b527-42010a800279
publish:
nodeId: …
```

chore(cvc): refactor cstorvolumeclaim schema

---

pkg/apis/openebs.io/core/v1alpha1/csivolume.go
pkg/generated/clientset/core/internalclientset/typed/core/v1alpha1/csivolume.go
pkg/generated/clientset/core/internalclientset/typed/core/v1alpha1/fake/fake_csivolume.go
pkg/service/v1alpha1/node.go
pkg/service/v1alpha1/service.go
pkg/utils/v1alpha1/kubernetes.go
pkg/volume/v1alpha1/build.go

This PR fixes the issue when Kubernetes sends a Publish Volume request on a node for a new pod with same VolumeID before unpublishing the old one.
Following changes have been implemented:
1) Status field has been added to CSI Volume CR.
2) Mountpath is also being compared
3) CSI Volume CRs are being read while coming up

Add Status field to CSIVolume API and read CSIVolumeCRs while coming up

---

ci/ci-test.sh
pkg/service/v1alpha1/controller.go
pkg/utils/v1alpha1/maya.go

1. This commit gets `CStorPoolCluster` name from storageclass parameters
and set as label in `cstorvolumeclaim` resource which will be used to
distribute the replica in cstorpool instances.
2. Get the `cas-type` from storageclass and populate as VolumeContext info.
this parameter is needed to differentiate b/w different openebs volume types i.e. `cstor` and `jiva` etc.
**StorageClass example**:
```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: cstor-sparse-auto
provisioner: openebs-csi.openebs.io
allowVolumeExpansion: true
parameters:
replicaCount: "1"
cstorPoolCluster: "cspc-sparse-pool"
cas-type: "cstor"
```
**CStorVolumeClaim example**:
```yaml
apiVersion: openebs.io/v1alpha1
kind: CStorVolumeClaim
metadata:
annotations:
openebs.io/volumeID: …
```

refact(cvc): use cstorPoolCluster name instead of storagePoolClaim

---

.travis.yml
deploy/csi-operator-ubuntu-18.04.yaml
deploy/csi-operator.yaml

Resize support has been added as part of `1.15`  kuberntes version as feature gate enable which required to bump the travis k8s version to `1.15+`
This change missed to as part of resize BDD changes.

refact(travis): bump minikube version 1.4.0 to use k8s v1.16.0

---

.travis.yml
deploy/csi-operator-ubuntu-18.04.yaml
deploy/csi-operator.yaml

Resize support has been added as part of `1.15`  kuberntes version as feature gate enable which required to bump the travis k8s version to `1.15+`
This change missed to as part of resize BDD changes.
- update k8s version 1.16.0
- update k8s API's kind for statefulset and daemontset to use `apps/v1`
Cherry-pick #39 

refact(travis): bump minikube version v1.4.0 to use k8s v1.16.0

---

Makefile

Image name has been changed from `openebs/csi-driver` to
`openebs/cstor-csi-driver`
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>

fix(Makefile): update image name in push target

---

pkg/service/v1alpha1/node.go
pkg/utils/v1alpha1/kubernetes.go

There will be unpublish events request in each ~60s periods for
stale/orphaned volume which was causing node driver crash
due to **NO** `CSIVolume` resource exists for the requested `volumeID`.
Err:
```
time="2019-11-08T09:51:33Z" level=info msg="GRPC call: /csi.v1.Node/NodeUnpublishVolume"
time="2019-11-08T09:51:33Z" level=info msg="GRPC request: {\"target_path\":\"/var/lib/kubelet/pods/270e7e5d-b068-4e43-bb22-ffbb128e933a/volumes/kubernetes.io~csi/pvc-5f0c7003-b840-4fcd-956f-70f1c58966f0/mount\",\"volume_id\":\"pvc-5f0c7003-b840-4fcd-956f-70f1c58966f0\"}"
time="2019-11-08T09:51:33Z" level=error msg="GRPC error: rpc error: code = Internal desc = csivolumes.openebs.io \"pvc-5f0c7003-b840-4fcd-956f-70f1c58966f0\" not found"
time="2019-11-08T09:53:35Z" level=info msg="GRPC call: …
```

fix(csi-node): return error for orphaned volume during unpublish event

---

deploy/busybox-csi-cstor-sparse.yaml

Need to change the unit size as well, else PV and PVC size will be in 5Gi and cStor volume size in 4Gi.
Reference:
```
ranjith_raveendran@cloudshell:~ (strong-eon-153112)$ kubectl get pvc
NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS             AGE
demo-csivol-claim   Bound    pvc-723283b6-02bc-11ea-a139-42010a8000b2   5Gi        RWO            openebs-csi-cstor-disk   17m
ranjith_raveendran@cloudshell:~ (strong-eon-153112)$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                       STORAGECLASS             REASON   AGE
pvc-723283b6-02bc-11ea-a139-42010a8000b2   5Gi        RWO            Delete           Bound    default/demo-csivol-claim …
```

refact(docs): update storage requests unit size

---

README.md
pkg/service/v1alpha1/service.go

To enable the auto remount feature when the volume goes into read only mode, REMOUNT env can be added to the csi node driver section in csi operator yaml:
```
kind: DaemonSet
apiVersion: apps/v1
metadata:
name: openebs-cstor-csi-node
namespace: kube-system
spec:
selector:
matchLabels:
app: openebs-cstor-csi-node
template:
metadata:
labels:
app: openebs-cstor-csi-node
role: openebs-cstor-csi
spec:
priorityClassName: system-node-critical
serviceAccount: openebs-cstor-csi-node-sa
hostNetwork: true
containers:
- name: csi-node-driver-registrar
image: quay.io/k8scsi/csi-node-driver-registrar:v1.0.1
imagePullPolicy: IfNotPresent
args:
- "--v=5"
- "--csi-address=$(ADDRESS)"
- "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
lifecycle:
preStop:
exec:
command: ["/bin/sh", "-c", "rm -rf …
```

Add(env): Add environment variable to enable remount feature

---

buildscripts/cstor-csi-driver/Dockerfile

This PR installs xfsprogs inside the container running csi plugin services.
fsType can be added to storage class parameters. Default fsType is ext4
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
name: cstor-csi-sc
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
parameters:
cas-type: cstor
replicaCount: "1"
cstorPoolCluster: cstor-sparse-cspc
fsType: xfs
``` 

Add support for xfs filesystem

---

pkg/utils/v1alpha1/maya.go
pkg/utils/v1alpha1/rounding.go

fixes the `G` to `bytes` to `Gi` conversion while trasitioning from PVC to CVC storage capacity the way kubernetes handles, by converting to Gi form.
here is the example link for the same https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/volume/helpers/rounding.go
Note:  roundUpSize calculates how many allocation units are needed to accommodate
a volume of given size. E.g. when user wants 1500MiB volume, while AWS
EBS,GKE etc allocates volumes in gibibyte-sized chunks,
RoundUpSize(1500 * 1024*1024, 1024*1024*1024) returns '2'
(2 GiB is the smallest allocatable volume that can hold 1500MiB)
1. PVC yaml
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: claim-csi-123
spec:
storageClassName: cstor-sparse-auto
accessModes:
- ReadWriteOnce …
```

refact(size): conversion G to Gi

---

pkg/utils/v1alpha1/utils.go

This PR adds a check in remount for empty staging and publish paths.
The CSIVolume CR creation has been shifted to ControllerPublish from NodePublish.
When CSIVolume CR is created at ControllerPublish, Staging and TargetPath are empty, therefore remount thread should not monitor this volume until a valid staging and targetpath are filled in. These paths are filled in nodeStage and NodePublish APIs.

fix(remount): Avoid monitoring volume unless mounted

---

pkg/service/v1alpha1/node.go
pkg/service/v1alpha1/node_utils.go

Changes include CSI volume metrics support which can be pulled by promethues exporter to show the metrics in k8s cluster.
Currently to verify the metrics , node plugin logs can be checked.
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>

feat(csi-metrics): add metrics support for volumes

---

pkg/iscsi/v1alpha1/iscsi_util.go
pkg/service/v1alpha1/node.go

This PR addresses the issue when filesystem gives IO error on doing a os.Stat() on the path.
In this case unmount was not being tried on the mountpoint even though the volume was mounted.
**dmesg:**
```
[44783.894404] print_req_error: I/O error, dev sdb, sector 5242752 flags 1801
[44783.901484] XFS (sdb): metadata I/O error in "xlog_iodone" at daddr 0x4fff80 len 64 error 5
[44783.909995] XFS (sdb): xfs_do_force_shutdown(0x2) called from line 1271 of file /build/linux-gcp-2nu89i/linux-gcp-5.0.0/fs/xfs/xfs_log.c. Return address = 0000000039615018
[44783.909997] XFS (sdb): Log I/O Error Detected. Shutting down filesystem
[44783.916775] XFS (sdb): Please unmount the filesystem and rectify the problem(s)
```
**kubectl describe po**
```
Normal   Scheduled    8m6s …
```

fix(unmount): Fix unmount errors for xfs filesystem

---

ci/ci-test.sh
pkg/service/v1alpha1/controller.go
pkg/utils/v1alpha1/maya.go

Changes gets the cstorvolumepolicy name from the storageclass
parameters and sets the annotations in Cstorvolumeclaim to get
it further used in configure cstorvolume target pods, etc
Example:
```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: cstor-sparse-auto
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
parameters:
replicaCount: "1"
cstorPoolCluster: "cspc-sparse"
cas-type: "cstor"
cstorVolumePolicy: "csi-volume-policy"
```

feat(csi): get cstorvolume policy from the SC parameters

---

deploy/csi-operator-ubuntu-18.04.yaml
deploy/csi-operator.yaml

with csi provisioner 1.4.0 changes volumesnapshot status has to be allowed to update the snapshot status, which is failing earlier due to missing status resource not exists.

fix(csi, snapshot): enable status subresource in VolumeSnapshot CRD

---

deploy/csi-operator-ubuntu-18.04.yaml
deploy/csi-operator.yaml
deploy/csidriver.yaml
deploy/snapshot-class.yaml
examples/csi-snapshot.yaml
pkg/service/v1alpha1/controller.go
pkg/service/v1alpha1/controller_utils.go

- update the csi-snapshotter volumesnapshot and
volumesnapshotcontent CRD's to v1beta1 APIs
- Add openAPI validations in snapshot CRD's
- add snapshot controller statefulsets container as part of v1beta1
stable APIs
- Update csi snapshotter and provisioner image to required
versions
**CSIDriver Resource**
The CSIDriver Kubernetes API object serves two purposes:
-  Simplify driver discovery : 
If a CSI driver creates a CSIDriver object, Kubernetes users can easily discover the CSI Drivers installed on their cluster (simply by issuing kubectl get CSIDriver)
- Customizing Kubernetes behavior:
Kubernetes has a default set of behaviors when dealing with CSI Drivers (for example, it calls the Attach/Detach operations by default). This object allows CSI drivers to specify how Kubernetes should …

fix(csi): handle duplicate snapshot request and support Snapshot V1beta1 APIs

---

pkg/utils/v1alpha1/utils.go

This commit fixes the issue where goroutine get blocked on TransitionVolListLock.Lock() upon error because of break statement.
Signed-off-by: Utkarsh Mani Tripathi <utkarsh.tripathi@mayadata.io>

fix(cstor-csi): dealock in monitor mount goroutine

---

deploy/csi-operator-ubuntu-18.04.yaml
pkg/iscsi/v1alpha1/iscsi_util.go
pkg/iscsi/v1alpha1/mount.go
pkg/service/v1alpha1/node.go

This PR addresses the issue of rescan commands getting stuck because of some stale iscsi sessions.
Initially, on receiving a resize filesystem command, rescan was being performed for all iSCSI sessions which will now be run only for volume being resized.

Run rescan only for volume being resized

---

pkg/driver/controller.go
pkg/driver/node.go
pkg/driver/node_utils.go
pkg/driver/utils.go

This fix required in case if there is difference between actual nodeName and `kubernetes.io/hostname` label in k8s clusters . for example aws based k8s cluster have similar results
This difference causes plugin registration failed due to topology collision while updating Node object with CSI driver node info
for example in AWS based cluster
driver reported "kubernetes.io/hostname":"ip-192-168-45-94.ap-south-1.compute.internal"
but existing label is "kubernetes.io/hostname":"ip-192-168-45-94"

fix(topology): add customized topology key for node name

---

.travis.yml
Makefile
buildscripts/build.sh
buildscripts/cstor-csi-driver/Dockerfile
buildscripts/cstor-csi-driver/entrypoint.sh
buildscripts/push
buildscripts/test-cov.sh
buildscripts/test.sh
buildscripts/tools.go
buildscripts/travis-build.sh

PR makes docker images configurable and removes the leading 'v' from image tags. This is required to make the image name consistent with other openebs images
**Special notes for your reviewer**: 
NA
**Checklist**

refact(build): make the docker images configurable

---

pkg/driver/node.go
pkg/driver/service.go
pkg/utils/kubernetes.go
pkg/utils/utils.go

Finalizer can be left on CStorVolumeAttachment CR in the following cases:
1. Unsuccessful attach/mount 
2. NodeRestarts
3. Driver crashes after unmounting the volume.
In the above cases the volume is not mounted due to which, kubelet doesn't send a Unstage request.
This PR implements the following to address these issues:
1. Remove finalizer if the volume attach/mount fails
2. Unmount/Detach volumes and remove finalizer if DeletionTimestamp is set on corresponding CStorVolumeAttachment CR on driver restarts.

fix(CStorVolumeAttachment): Remove finalizer on unsuccesful mounts and on driver restarts

---

buildscripts/build.sh
pkg/utils/maya.go

Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>
This PR does the following changes
- Removes the dependency with CVC Version during volume
provisioning.
- Updates the VERSION variable with ${CURRENT_BRANCH_NAME}-dev
during build time
**Why we need this PR**:
This PR is required to break the dependency with CVC-Operator
during volume provisioning. Below are the existing steps performed
during volume provisioning:
- CSI driver receives volume create requests and creates CVC with VERSION details
- CVC controller will reconcile for CVCs only if `cvc.VersionDetails.Status.Current`
matches to VERSION value in CVC controller. If reconciliation doesn't happen then
CStorVolume resources will not create hence the application will not get OpenEBS volume.
**Which …

fix(VERSION): remove version dependency during volume provisioning

---

pkg/cstor/volumeconfig/build.go
pkg/utils/maya.go

commit add the persistent volume claim name annotation in CVC resource while provisioning, requires to set
in volume target deployments.
**Checklist**

refact(cvc): add pvc annotation during provisioning

---

deploy/csi-operator.yaml
pkg/driver/node.go
pkg/driver/node_utils.go

Mount `/` partition under `/host` directory inside the container
and use chroot to run iscsiadm under `/host` directory so that
it can find all necessary shared libraies it depends on.
For more info refer: https://github.com/openebs/cstor-operators/pull/119
Also handles the dual mount paths exists due to root reference mount
```sh
mount | grep pvc
/dev/sdd on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-42d5a9a5-4403-44a3-a962-ad0162a0fa8d/globalmount type ext4 (rw,relatime,stripe=256)
/dev/sdd on /host/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-42d5a9a5-4403-44a3-a962-ad0162a0fa8d/globalmount type ext4 (rw,relatime,stripe=256)
```
**Special …

refact(operator): mount host root partition inside container

---

deploy/csi-operator.yaml
deploy/snapshot-class.yaml

Install csi driver in `openebs` namespace instead of `kube-system` namespace
**Checklist**

chore(operator): install csi driver in openebs  ns instead of kube-system

---

pkg/driver/node.go
pkg/iscsi/iscsi_util.go
pkg/utils/server.go

- Handle the mount reference count due to root mount inside the node daemonset container.
iSCSI logout was being avoided due to Multiple references to staging path causes the stale iscsi sessions.
- iSCSI stale session in case node-plugin get restarted in between
- Added error checks to handle the iscsi errors  in retry cases
- Fix the iscsi logs
**Checklist**

fix(NodeUnstage): avoid stale iscsi sessions

---

ci/ci-test.sh
pkg/driver/controller_utils.go

Commits adds the validation to validate the create volume request access mode and support only single node writer
i.e. `ReadWriteOnce` accessmode and failed for other unsupported modes, like `ReadWriteMany`
- Tested the changes using a `ReadWriteMany` accessmode PVC and verify the error.
```yaml
kubectl describe pvc
Name:          claim-csi-123
Namespace:     default
StorageClass:  cstor-sparse-auto
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: cstor.csi.openebs.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
Type     Reason                Age …
```

fix(create): validate create volume request access mode

---

ci/ci-test.sh

update github fetch link for cstor-operators crds which are no longer exists in older path at master branch
pointed to v1.12.x branch for release specific crd yamls.

fix(travis): update cstor operators CRDs reference

---

Makefile
go.sum

commit fixes the build dependencies to be fetch in different directory instead of root dir. fetching at root dir updates the
go.mod,go.sum results dependency verification check to be failed.

fix(build): update Makefile to go get deps in different dir 

---

pkg/apis/cstor/v1/csivolume.go
pkg/utils/utils.go

When the remount feature is enabled process will be monitoring for mount points on that node. If mount points are marked as RO, process will launch `go routines`  for them in a loop. Since these go routine are using the same stack variable `vol` when the loop iterates, change in value of the variable will lead to volumes not getting removed from transition list.

fix(remount): resolve race condition in remount code

---

pkg/apis/cstor/v1/csivolume.go
pkg/utils/utils.go

When the remount feature is enabled process will be monitoring for mount points on that node. If mount points are marked as RO, process will launch go routines for them in a loop. Since these go routine are using the same stack variable vol when the loop iterates, change in value of the variable will lead to volumes not getting removed from transition list.

cherry-pick(remount-fix): resolve race condition in remount code

---

pkg/driver/node.go
pkg/driver/utils.go

PR adds the csi volums metrics support for block volumes , so that these matrics can me exposed via promethus running in a cluster

feat(metrics): add volumes metrics support for raw block volume

---

Makefile.buildx.mk
buildscripts/push

Enabling more than two arch in the multi-arch builds
is resulting in increased build times as well as
intermittent failures in running the builds.
Limiting to two archs - amd64 and arm64 for now.
Ran the actions with various combinations:
Observations:
2 arches complete within 10 mins and all 3 runs tried were successful. 
3 arches take about 30 mins - 1 in 3 builds passed
4 arches take about 30+ mins, 1 in 5 builds passed
Signed-off-by: kmova <kiran.mova@mayadata.io>

refact(build): run only amd64 and arm64 builds

---

tests/e2e/e2e_test.go

PR remove the resize failure events check to verfiy there is only 1 resize fail event, which may take more then 1 event cycle to complete the resize of PVC sometimes , causes the failure in travis.

refact(tests): remove hard check for single resize failure events

---

.github/workflows/build.yml
.github/workflows/release.yml
Makefile
buildscripts/cstor-csi-driver/cstor-csi-driver.Dockerfile

- pass RELEASE_TAG and BRANCH as build args to buildkit container
- replace deprecated methods in github actions
**Checklist**

chore(build): propogate envs to buildkit container

---

ci/ci-test.sh
deploy/csi-operator.yaml
tests/e2e/run_test.go

- Bump k8s csi sidecar container image to latest stable  releases minimum kubernetes version to support 1.17
-  Remove the deprecated Cluster Driver Registrar container which is no longer required since the `CSIDriver` object instance should be created by CSI driver installer (or manually)
- Update the Snapshot specific CRDs to `V1` version
**Checklist**

chore(operator): bump k8s csi to latest stable container images

---

.github/workflows/build.yml
.github/workflows/release.yml
tests/e2e/run_test.go

add/install the ginko dependencies in build and release github action workflows ( build and release), which was missed to add as part of earlier changes. 
https://github.com/openebs/cstor-csi/blob/13a0d2316ded0e96a517940a366db3440914b2a8/.github/workflows/pull_request.yml#L89

fix(action): add missing ginkgo dependencies in build workflow

---

go.mod
pkg/driver/node.go
pkg/driver/node_utils.go
pkg/driver/service.go
pkg/driver/utils.go
pkg/utils/kubernetes.go
pkg/utils/utils.go

This PR addresses the following:
1. Handle clean up errors on node restarts
2. Monitor and remove stale cstorVolumeAttachment objects. To handle cases when kubelet doesn't send unstage requests on node reboots.
3. Avoid patching nodeID to CVC object every time the volume is staged. This may cause issues when the application pod is moved to a new node. Updating CVC requires the admission server to be reachable.
4. Improve logging 

fix(cleanup): add cleanup of volumes from node  to monitor func

---

go.mod
pkg/driver/node.go
pkg/driver/node_utils.go
pkg/driver/service.go
pkg/driver/utils.go
pkg/utils/kubernetes.go
pkg/utils/utils.go

This PR addresses the following:
1. Handle clean up errors on node restarts
2. Monitor and remove stale cstorVolumeAttachment objects. To handle cases when kubelet doesn't send unstage requests on node reboots.
3. Avoid patching nodeID to CVC object every time the volume is staged. This may cause issues when the application pod is moved to a new node. Updating CVC requires the admission server to be reachable.
4. Improve logging

cherry-pick(cleanup-fix): add cleanup of volumes from node  to monitor func (#142)

---

.github/workflows/build.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml

Signed-off-by: Niladri Halder <niladri.halder@mayadata.io>
The build.yml and pull_request.yml workflows will ignore pushes made to `docs/` and `changelogs/` directories, all `.md` files, LICENSE and MAINTAINERS files.
Added criteria to ignore build workflows on release. 
Added Build & Push Actions jobs instead of Build & Push via makefile

chore(github-action): Refine GitHub Actions criteria and add Build & Push jobs

---

pkg/driver/node_utils.go
pkg/kubernetes/node/kubernetes.go

This PR allows discovery & login to iSCSI volume only from one node at any given time.
This PR handles below case:
- Only one pod will get an iSCSI volume if multiple pods
instances consume the same volume from different nodes at any time.
Limitations:
- If multiple pod instances of different nodes perform NodeStaging
request same time then both will succeed in the operation but only
one can perform IOs.
- Canary deployments model & Rolling update strategy deployment will
not work as-is(As a workaround old pods needs to be deleted) they
will remain in a pending state.
- Multiple pod instances of same (or) different deployments can run on same
node(If we add checks then the rolling update strategy will never work).
NOTE:
- To avoid limitation 1 we need to add …

fix(mount): allow staging of cStor volume only from one node

---

pkg/driver/node_utils.go

This PR updates the error message during NodeStage request time
to show the node name where the volume is already mounted.
**Existing Pod**:
```sh
$ kubectl get po -A -o wide
NAMESPACE     NAME                                                              READY   STATUS              RESTARTS   AGE     IP             NODE              NOMINATED NODE   READINESS GATES
default       percona-69fb95ccb4-qvm6p                                          1/1     Running             0          31m     10.244.1.112   centos-worker-1   <none>           <none>
default       percona-86b789d974-5xgkk                                          0/1     ContainerCreating   0          5s      <none>         centos-master     <none>           <none>
```
**Describe of pod in container …

fix(log): update error log message during NodeStage request

---

deploy/csi-operator.yaml

Update the k8s csi sidecar images to support minimum k8s 1.18+ version.
- CSI Provisioner:
k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
- CSI Resizer:
k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
- CSI Node Driver Registrar
k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
- CSI Volume Monitor
k8s.gcr.io/sig-storage/csi-external-health-monitor-controller:v0.4.0
**Note**:  Keeping the Snapshotter version as same as earlier , since the latest version only support the V1 snaphot apis , and cloud k8s distribution, openshift etc does not supported the v1 snapshot APIs yet.
With current snapshotter 3.0.3 version we have advantage that it will support both v1beta1/v1 apis, which will work in most of the cloud/openshift
Signed-off-by: prateekpandey14 …

chore(operator): bump k8s csi sidecars images

---

.github/pull_request_template.md
.github/workflows/build.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
CONTRIBUTING.md
GOVERNANCE.md
RELEASE.md
buildscripts/push
ci/ci-test.sh
deploy/archive/csi-operator-ubuntu-18.04.yaml
docs/code-standard.md
docs/developer-setup.md

* chore(doc): updating branch reference from master to develop(HEAD)
This commit updates the reference from master to develop in scripts
and *.md files. Following are the files
- CONTRIBUTING.md
- GOVERNANCE.md
- RELEASE.md
- docs/code-standard.md
- docs/developer-setup.md
- .github/pull_request_template.md
- buildscripts/push
- ci/ci-test.sh
- deploy/archive/csi-operator-ubuntu-18.04.yaml
* This commit updates the GitHub workflow references from master to develop
* This commit add ghcr  container repository to host container images
Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>

chore(doc): updating branch reference from master to develop(HEAD)
