.bettercodehub.yml
.golangci.yml
.travis.yml

This commit adds following build & linting tools against this project:
- travis
- bettercodehub
- golangci

chore(lint): add travis, bettercodehub and golangci integrations

---

.travis.yml
Makefile
buildscripts/test-cov.sh
buildscripts/test.sh

fix(travis): update travis build

---

deploy/csi-operator.yaml

Add csi driver, node-plugin, snapshotter, external-attacher, CRD's
service accounts and required ClusterRole and ClusterRoleBindings

feat(csi, operator): add csi driver, attacher, node-plugin, and conroller

---

.travis.yml
Makefile
ci/ci-test.sh

These BDD tests will reside in [maya](https://github.com/openebs/maya) repo

Run CSI BDD tests in travis

---

pkg/apis/openebs.io/maya/v1alpha1/cstor_volume.go
pkg/cstor/volume/v1alpha1/build.go
pkg/cstor/volume/v1alpha1/cstorvolume.go
pkg/cstor/volume/v1alpha1/kubernetes.go

In this PR builder pattern for cstor volume has been fetched from maya repo.

Add cstor volume builder pattern

---

.travis.yml
Makefile
ci/ci-test.sh
pkg/service/v1alpha1/controller.go
pkg/utils/v1alpha1/maya.go

- Remove configClass reference from CVC 
- Add replicaCount and StoragePoolClaim parameter validations.
- Pull the latest openebs-operator file to deploy openebs
components for integration tests

refact(cvc):remove configclass reference from CVC and add validations

---

README.md
deploy/pvc.yaml
deploy/sc.yaml
deploy/spc.yaml

This PR illustrates an example to provision a volume and deploy an app using the same.

update(README): Add steps to provision a volume

---

README.md
deploy/busybox-csi-cstor-sparse.yaml
deploy/csi-operator-ubuntu-18.04.yaml
deploy/sc.yaml
deploy/spc.yaml

Refactored the usage instructions to provide few additional
details and verification steps.
Signed-off-by: kmova <kiran.mova@mayadata.io>

docs(readme): update usage instructions for OpenEBS 1.1.0

---

pkg/apis/openebs.io/core/v1alpha1/csivolume.go
pkg/iscsi/v1alpha1/iscsi_util.go
pkg/iscsi/v1alpha1/mount.go
pkg/service/v1alpha1/node.go
pkg/service/v1alpha1/service.go
pkg/utils/v1alpha1/kubernetes.go
pkg/utils/v1alpha1/utils.go

This PR reduces the dependency on CSIVolumeCR to a very large extent.
This was done to avoid corner cases and make the code simpler to read.

refactor(publish/unpublish): Refactor code for node publish and unpublish

---

README.md

This PR updates the docs to:
1. Provision pools via cspc instead of spc.
2. Expand cStor volumes using OpenEBS CSI driver

update(readme): Update readme based on the recent csi changes

---

.travis.yml

- Update travis api secure key
- bump go version to 1.12.9

fix(travis): update travis api secure key

---

.travis.yml

Commit remove travis github deploy as its not required further.

refact(travis): remove travis github release deploy

---

pkg/iscsi/v1alpha1/iscsi_util.go
pkg/iscsi/v1alpha1/mount.go
pkg/service/v1alpha1/controller_utils.go
pkg/service/v1alpha1/node.go
pkg/service/v1alpha1/utils.go

fix(resize): Add command to resize xfs volumes

---

deploy/csi-operator-ubuntu-18.04.yaml
deploy/csi-operator.yaml
pkg/service/v1alpha1/controller.go
pkg/service/v1alpha1/node.go
pkg/service/v1alpha1/node_utils.go
pkg/utils/v1alpha1/maya.go

feat(topology): Add topology support for cstor csi volumes

---

CHANGELOG.md

chore(changelog): add CHANGELOG file with all the changes

---

deploy/csi-operator-ubuntu-18.04.yaml
deploy/csi-operator.yaml

- add openebs.io/version label is deployments
- update openebs.io/components labels to make it
consistent with other openebs operators
**Checklist**

refact(operator): add version and components labels in deployments

---

pkg/driver/node.go
pkg/driver/service.go
pkg/utils/kubernetes.go
pkg/utils/utils.go

fix(CStorVolumeAttachment): Remove finalizer on unsuccesful mounts and on driver restarts (#82)

---

pkg/driver/controller.go

fixes the snapshot delete logs 
**Checklist**

fix(snapshot): update snapshot delete logs

---

CHANGELOG.md

Update change logs with 1.11.0 changes
Fixes #<issue number> NA
**Checklist**

chore(docs): add 1.11.0 changelog changes

---

pkg/cstor/volumeconfig/build.go

fix(log): fix typo in builder error logs

---

deploy/csi-operator.yaml
pkg/driver/node.go
pkg/driver/node_utils.go

Mount `/` partition under `/host` directory inside the container
and use chroot to run iscsiadm under `/host` directory so that
it can find all necessary shared libraies it depends on.
Cherry-pick: #101 
**Checklist**

refact(operator): mount host root partition inside container (#101)

---

ci/ci-test.sh
pkg/driver/controller_utils.go
pkg/driver/node.go
pkg/iscsi/iscsi_util.go
pkg/utils/server.go

This PR contains the cherry-pick of #108 and #109 
**Checklist**

cherry-pick(fix): cherry-pick of PR #109 and #108

---

tests/e2e/e2e_test.go

add clone pvc delete test to verify the webhook validations
**Checklist**

refact(test): add clone pvc delete test to verify the webhook validations

---

CHANGELOG.md

chore(docs): add 2.0.0 release CHANGELOG

---

pkg/utils/utils.go

This PR returns the Remount call immediately if volume
is not available/reachable. Currently it waits for 12 seconds
if volume is not ready and this will cause delay in mounting
the same application volume if application pod deleted/scaleup/scaledown.
Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>
**Checklist**

fix(remount): return immediately if volume is not ready for mounting in case of remount feature is enabled

---

.travis.yml
Makefile
buildscripts/install_go.sh
cmd/main.go
pkg/cstor/volumeconfig/utils.go
pkg/driver/controller_utils.go
pkg/driver/node_utils.go
pkg/driver/utils.go
pkg/iscsi/iscsi_extra_utils.go
pkg/iscsi/mount.go
pkg/utils/maya.go
pkg/utils/test/rounding_test.go
pkg/utils/utils.go
tests/e2e/Makefile
tests/e2e/e2e_test.go
tests/e2e/publish_test.go
tests/e2e/run_test.go
tests/e2e/suite_test.go

Signed-off-by: ajeetrai707 <ajeetrai707@gmail.com>
This PR is to Add license-check for .go , .sh , Dockerfile and Makefile.
**Checklist**

Add license-check for .go , .sh , Dockerfile and Makefile

---

CHANGELOG.md

Signed-off-by: Ashutosh Kumar <ashutosh.kumar@mayadata.io>

chore(changelog): add changelog for 2.1.0

---

CHANGELOG.md

Signed-off-by: Ashutosh Kumar <ashutosh.kumar@mayadata.io>

chore(changelog): add changelog for 2.2.0 RC1

---

.github/workflows/build.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
.travis.yml
Makefile
Makefile.buildx.mk
buildscripts/build.sh
buildscripts/cstor-csi-driver/Dockerfile
buildscripts/cstor-csi-driver/cstor-csi-driver.Dockerfile
buildscripts/cstor-csi-driver/entrypoint.sh
buildscripts/push

feat(build): support for multi arch container image

---

.github/workflows/build.yml
.github/workflows/release.yml
Makefile
buildscripts/cstor-csi-driver/cstor-csi-driver.Dockerfile

- replace deprecated method in github action workflows
- pass RELEASE_TAG and BRANCH and build arguments to buildkit container
**Checklist**

chore(build): fix buildscript and github action workflows

---

CHANGELOG.md
changelogs/released/v2.3.0-RC1/125-prateekpandey14
changelogs/released/v2.3.0-RC1/128-prateekpandey14

Signed-off-by: shubham <shubham.bajpai@mayadata.io>
This PR adds changelog for v2.3.0
**Checklist**

chore(CHANGELOG): add changelogs for v2.3.0

---

pkg/driver/controller.go
pkg/driver/node.go

Now user can label the nodes with the required custom topology, the cstor-csi  driver will support all the node labels as topology keys.
Ideally we should label the nodes first and then deploy the driver to make it aware of all the labels that node has been configured. 
If we want to add labels on the Nodes after CStor CSI driver has been deployed, a restart all the csi-node daemonset pods are required so that the driver can pick the labels and add them as supported topology keys.
**How the changes has been tested :**
1. Label all the similar nodes using the same key value and use that label to create the StorageClass
```sh
$ kubectl label node node-1 node-2 openebs.io/nodegroup=storage
```
2. Now, restart …

feat(topology): add support for custom topology keys

---

.travis.yml

chore(travis):bump minikube version to use k8s 1.20.1 version

---

.github/workflows/build.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
ci/ci-test.sh

bump the buildx version to use latest stable release v0.5.1. instead of latest.

chore(build): bump buildx action version v0.5.1

---

.github/workflows/build.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
ci/ci-test.sh
tests/e2e/Makefile
tests/e2e/run_test.go

Move all the e2e tests from the travis to github action ( still needs to increase the timeout values for the flaky builds)

chore(actions): move travis tests to github action

---

deploy/csi-operator.yaml
deploy/csidriver.yaml
pkg/driver/controller.go
pkg/driver/controller_utils.go
pkg/driver/node.go
pkg/driver/node_utils.go

fix(multi-attach): remove volume attach-detach functionality

---

deploy/csi-operator.yaml

Use k8s.gcr.io multi arch images for csi sidecars containers

chore(operator): use k8s.gcr.io multi arch images for csi sidecars

---

CHANGELOG.md
pkg/usage/ping.go

chore(changelog): add v2.6.0 changelogs

---

buildscripts/cstor-csi-driver/Dockerfile
buildscripts/cstor-csi-driver/cstor-csi-driver.Dockerfile

According to below document, ubuntu 16.04 has reached
it's EOL- https://wiki.ubuntu.com/Releases
Ref: https://github.com/openebs/openebs/issues/3386
**Checklist**

chore(build): use ubuntu 18.04 as container base image

---

README.md

Update repo docs and add community links in project README

refact(docs): update README with community and badges links

---

CHANGELOG.md

- Add 2.11.0 Changelogs
-  Also include the older release changelogs

chore(docs): add 2.11.0 release changelogs

---

pkg/driver/node_utils.go

This PR is chery-pick of #157 
**Checklist**
Signed-off-by: mittachaitu <sai.chaithanya@mayadata.io>

cherry-pick(log): update error log message during NodeStage request (#157)

---

.github/pull_request_template.md
.github/workflows/build.yml
.github/workflows/pull_request.yml
.github/workflows/release.yml
CONTRIBUTING.md
GOVERNANCE.md
RELEASE.md
buildscripts/push
ci/ci-test.sh
deploy/archive/csi-operator-ubuntu-18.04.yaml
docs/code-standard.md
docs/developer-setup.md

This PR does the following changes:
- Updates the reference from master to develop in scripts and *.md files
- Updates the GitHub workflow references from master to develop.
- Add ghcr container repository to host container images
**Checklist**

chore(doc): updating branch reference from master to develop(HEAD)
